# Generated by Django 5.2.1 on 2025-05-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourpackage_status_vendor_contact_email_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_reg_no',
            field=models.CharField(default='TEMP123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
            preserve_default=False,
        ),
    ]
