# Generated by Django 5.2.1 on 2025-05-19 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_vendor_business_reg_no_vendor_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='availability',
            field=models.PositiveIntegerField(default=0, help_text='Number of slots available'),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to archive instead of delete'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tourpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
