# Generated by Django 5.2.1 on 2025-05-19 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourpackage_availability_tourpackage_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourpackage',
            old_name='date_added',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='capacity',
            field=models.PositiveIntegerField(default=50, help_text='Maximum number of people allowed'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='tours.vendor'),
        ),
    ]
