# Generated by Django 5.2.1 on 2025-05-20 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_tourpackage_image_tourpackageimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booked_at',
            new_name='booking_date',
        ),
    ]
