# Generated by Django 5.2.1 on 2025-05-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('vendor', 'Vendor')], default='user', max_length=10),
        ),
    ]
